version: "3.9"

services: 
  backend: 
    container_name: backend
    build: 
      context: ..
      dockerfile: docker/backend.dockerFile
    ports:
      - "4000:4000"
    env_file:
      - ../apps/backend/.env

  frontend:
    container_name: frontend
    build:
      context: ..
      dockerfile: docker/frontend.dockerFile
    ports:
      - "80:80"
    env_file: 
      - ../apps/frontend/.env
     